### ISSUE TITLE
where is "Spatial Reference" data in timeseries excel file?

### ISSUE THREAD

**Issue by cdesyoun** [CZOData/YODA-File#52]
@horsburgh and @sreeder I am implementing to convert data in timeseries excel file into python objects (or, actually, ODM2 objects) using xlwings python package. Based on that, also YODA file can be generated. In your generated YODA file, this spatial reference data below was given. But, when looking into excel file, I can see only "SRSName" data in "Sampling Features" sheet.
In order to get other data for spatial reference, do you use the external interface?

```
SpatialReferences:
  - &SRSID0001 {SRSCode: "EPSG:4326", SRSName: "WGS84", SRSDescription: "Horizontal component of 3D system. Used by the GPS satellite navigation system and for NATO military geodetic surveying.", SRSLink: "http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4326"}
```

**Comment by horsburgh** [comment]
@cdesyoun - this is something that @SRGDamia1 implemented and we didn't change. There is a worksheet in the template that is currently hidden that is called "SpatialReferences". The drop down on the "SamplingFeatures" sheet is populated from that sheet, and when the YODA file is created, the details of the spatial reference are copied into the YODA file from the SpatialReferences worksheet.  It's hidden because there are only a couple of valid options and so I think @SRGDamia1 didn't want people to have to think about those details (or chance them getting them wrong).

**Comment by SRGDamia1** [comment]
Yes, exactly what Jeff said.

On 2/23/2016 10:31 AM, Jeff Horsburgh wrote:

> @cdesyoun https://github.com/cdesyoun - this is something that 
> @SRGDamia1 https://github.com/SRGDamia1 implemented and we didn't 
> change. There is a worksheet in the template that is currently hidden 
> that is called "SpatialReferences". The drop down on the 
> "SamplingFeatures" sheet is populated from that sheet, and when the 
> YODA file is created, the details of the spatial reference are copied 
> into the YODA file from the SpatialReferences worksheet. It's hidden 
> because there are only a couple of valid options and so I think 
> @SRGDamia1 https://github.com/SRGDamia1 didn't want people to have 
> to think about those details (or chance them getting them wrong).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ODM2/YODA-File/issues/52#issuecomment-187744667.

## 

Sara Geleskie Damiano
Technician
Stroud Water Research Center
970 Spencer Road
Avondale, PA 19311
(610) 268-2153 x 248

**Comment by cdesyoun** [comment]
@horsburgh and @SRGDamia1 Thank you so much for letting me know about hidden sheet list. I see several hidden sheet list on that timeseries excel file.
